### ISSUE TITLE
Create a prototype application for todo list application.

### ISSUE THREAD

**Issue by omarqx** [omarqx/todo#1]
define done: a dummy page that looks like todomvc.

story points 

- [ ] create npm project. (5 point)
- [ ] should have an html index (home) page. (3 points)
- [ ] basic css style for the home page (5 points)
- [ ] text box that accept new tasks. (3 points)
- [ ] list of tasks in page. (5 points)
- [ ] complete task box next to task name. (3 points)
- [ ] todo list footers. (5 points)

this should be based on [todomvc](http://todomvc.com/)
